export const baseUrl = "https://yourdomain.com/api";

export const allProducts = [
  {
    id: 1,
    name: "Product 1",
    subtitle: "Subtitle 1",
    category: 1,
    image: "https://picsum.photos/700",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 29.99,
    favourite: false,
  },
  {
    id: 2,
    name: "Product 2",
    subtitle: "Subtitle 2",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 49.5,
    favourite: true,
  },
  {
    id: 3,
    name: "Product 3",
    subtitle: "Subtitle 3",
    category: 2,
    image: "https://picsum.photos/700",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 19.75,
    favourite: false,
  },
  {
    id: 4,
    name: "Product 4",
    subtitle: "Subtitle 4",
    category: 2,
    image: "https://picsum.photos/700",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    price: 39.99,
    favourite: true,
  },
  {
    id: 5,
    name: "Product 5",
    subtitle: "Subtitle 5",
    category: 3,
    image: "https://picsum.photos/700",
    description:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    price: 25.0,
    favourite: false,
  },
  {
    id: 6,
    name: "Product 6",
    subtitle: "Subtitle 6",
    category: 4,
    image: "https://picsum.photos/700",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 59.95,
    favourite: true,
  },
  {
    id: 7,
    name: "Product 7",
    subtitle: "Subtitle 7",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 10.99,
    favourite: false,
  },
  {
    id: 8,
    name: "Product 8",
    subtitle: "Subtitle 8",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 32.4,
    favourite: true,
  },
  {
    id: 9,
    name: "Product 9",
    subtitle: "Subtitle 9",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    price: 45.6,
    favourite: false,
  },
  {
    id: 10,
    name: "Product 10",
    subtitle: "Subtitle 10",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    price: 75.99,
    favourite: true,
  },
  {
    id: 11,
    name: "Product 11",
    subtitle: "Subtitle 11",
    category: 1,
    image: "https://picsum.photos/700",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 27.89,
    favourite: false,
  },
  {
    id: 12,
    name: "Product 12",
    subtitle: "Subtitle 12",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 53.45,
    favourite: true,
  },
  {
    id: 13,
    name: "Product 13",
    subtitle: "Subtitle 13",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 18.99,
    favourite: false,
  },
  {
    id: 14,
    name: "Product 14",
    subtitle: "Subtitle 14",
    category: 1,
    image: "https://picsum.photos/700",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    price: 42.5,
    favourite: true,
  },
];

export const paymentMethods = [
  {
    bank: "Bank of America",
    cardNumber: "1234567812345678",
    expDate: "12/26",
    cardholder: "John Doe",
    provider: "Visa",
    type: "Credit",
  },
  {
    bank: "Chase",
    cardNumber: "2345678923456789",
    expDate: "11/25",
    cardholder: "Jane Smith",
    provider: "Mastercard",
    type: "Debit",
  },
  {
    bank: "Wells Fargo",
    cardNumber: "3456789034567890",
    expDate: "10/24",
    cardholder: "Alex Johnson",
    provider: "American Express",
    type: "Credit",
  },
];
